name: EventCoreLib
version: ${version}
main: com.smughito.eventcorelib.EventCoreLib
api-version: '1.21'
author: Smughito
description: Team management library for Minecraft event plugins
website: https://github.com/Smughito/EventCoreLib

softdepend:
  - LuckPerms
